import "./globals.css";
import type { Metadata } from "next";
import { Inter,Montserrat } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });
const monsterrat = Montserrat({subsets:["latin-ext"]});

export const metadata: Metadata = {
  title: "Next JS Image Gallery",
  description: "Generated by create next app",
};

//A root layout is the top-most layout in the root app directory. It is used to define the <html> and <body> tags and other globally shared UI.
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={monsterrat.className}>{children}</body>
    </html>
  );
}
